/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
See the source at https://github.com/ (Explorer Sort plugin).
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ExplorerSortPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// node_modules/monkey-around/mjs/index.js
function around(obj, factories) {
  const removers = Object.keys(factories).map((key) => around1(obj, key, factories[key]));
  return removers.length === 1 ? removers[0] : function() {
    removers.forEach((r) => r());
  };
}
function around1(obj, method, createWrapper) {
  const original = obj[method], hadOwn = obj.hasOwnProperty(method);
  let current = createWrapper(original);
  if (original)
    Object.setPrototypeOf(current, original);
  Object.setPrototypeOf(wrapper, current);
  obj[method] = wrapper;
  return remove;
  function wrapper(...args) {
    if (current === original && obj[method] === wrapper)
      remove();
    return current.apply(this, args);
  }
  function remove() {
    if (obj[method] === wrapper) {
      if (hadOwn)
        obj[method] = original;
      else
        delete obj[method];
    }
    if (current === original)
      return;
    current = original;
    Object.setPrototypeOf(wrapper, original || Function);
  }
}

// src/types.ts
var DEFAULT_DATA = {
  enabled: true,
  orders: {}
};

// src/reorderModal.ts
var import_obsidian = require("obsidian");
var ReorderModal = class extends import_obsidian.Modal {
  constructor(app, plugin, folder) {
    super(app);
    this.plugin = plugin;
    this.folder = folder;
    this.listEl = null;
    this.dragIndex = -1;
    this.names = plugin.getDisplayedChildNames(folder);
  }
  onOpen() {
    this.titleEl.setText(
      `Reorder: ${this.folder.path === "/" ? "Vault root" : this.folder.path}`
    );
    this.contentEl.createEl("p", {
      text: "Drag items to rearrange them, then save.",
      cls: "explorer-sort-hint"
    });
    this.listEl = this.contentEl.createDiv({ cls: "explorer-sort-list" });
    this.renderList();
    new import_obsidian.Setting(this.contentEl).addButton(
      (btn) => btn.setButtonText("Reset to default sorting").onClick(async () => {
        await this.plugin.clearOrder(this.folder);
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Save order").setCta().onClick(async () => {
        await this.plugin.setOrder(this.folder, this.names);
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
  renderList() {
    const list = this.listEl;
    if (!list)
      return;
    list.empty();
    const isFolder = (name) => this.folder.children.find((c) => c.name === name) instanceof import_obsidian.TFolder;
    this.names.forEach((name, index) => {
      const row = list.createDiv({ cls: "explorer-sort-row" });
      row.draggable = true;
      row.createSpan({ cls: "explorer-sort-grip", text: "\u283F" });
      row.createSpan({
        cls: "explorer-sort-name",
        text: isFolder(name) ? `\u{1F4C1} ${name}` : name
      });
      const controls = row.createDiv({ cls: "explorer-sort-controls" });
      const upBtn = controls.createEl("button", { text: "\u2191" });
      upBtn.disabled = index === 0;
      upBtn.addEventListener("click", () => this.moveTo(index, index - 1));
      const downBtn = controls.createEl("button", { text: "\u2193" });
      downBtn.disabled = index === this.names.length - 1;
      downBtn.addEventListener("click", () => this.moveTo(index, index + 1));
      row.addEventListener("dragstart", (evt) => {
        var _a;
        this.dragIndex = index;
        row.addClass("is-dragging");
        (_a = evt.dataTransfer) == null ? void 0 : _a.setData("text/plain", name);
        if (evt.dataTransfer)
          evt.dataTransfer.effectAllowed = "move";
      });
      row.addEventListener("dragend", () => {
        this.dragIndex = -1;
        row.removeClass("is-dragging");
      });
      row.addEventListener("dragover", (evt) => {
        evt.preventDefault();
        if (this.dragIndex === -1 || this.dragIndex === index)
          return;
        row.addClass("is-drop-target");
      });
      row.addEventListener("dragleave", () => row.removeClass("is-drop-target"));
      row.addEventListener("drop", (evt) => {
        evt.preventDefault();
        row.removeClass("is-drop-target");
        if (this.dragIndex === -1 || this.dragIndex === index)
          return;
        this.moveTo(this.dragIndex, index);
      });
    });
  }
  moveTo(from, to) {
    if (to < 0 || to >= this.names.length)
      return;
    const [moved] = this.names.splice(from, 1);
    this.names.splice(to, 0, moved);
    this.dragIndex = -1;
    this.renderList();
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var ExplorerSortSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Enable custom sorting").setDesc(
      "When enabled, folders with a saved custom order are displayed in that order. Items without a saved position (e.g. newly created files) are appended at the bottom."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.data.enabled).onChange(async (value) => {
        this.plugin.data.enabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Custom orders").setDesc(
      `${Object.keys(this.plugin.data.orders).length} folder(s) currently have a custom order. Right-click a file or folder in the explorer to move it, or use \u201CReorder folder contents\u2026\u201D for drag-and-drop.`
    ).addButton(
      (btn) => btn.setButtonText("Clear all custom orders").setWarning().onClick(async () => {
        await this.plugin.clearAllOrders();
        new import_obsidian2.Notice("Explorer Sort: all custom orders cleared");
        this.display();
      })
    );
  }
};

// src/main.ts
var ExplorerSortPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.data = DEFAULT_DATA;
    this.uninstallPatch = null;
  }
  async onload() {
    var _a;
    this.data = Object.assign({}, DEFAULT_DATA, await this.loadData());
    this.data.orders = (_a = this.data.orders) != null ? _a : {};
    this.addSettingTab(new ExplorerSortSettingTab(this.app, this));
    this.registerFileMenu();
    this.registerVaultEvents();
    this.registerCommands();
    this.app.workspace.onLayoutReady(() => {
      if (!this.patchFileExplorer()) {
        const evt = this.app.workspace.on("layout-change", () => {
          if (this.patchFileExplorer()) {
            this.app.workspace.offref(evt);
          }
        });
        this.registerEvent(evt);
      }
    });
  }
  onunload() {
    var _a;
    (_a = this.uninstallPatch) == null ? void 0 : _a.call(this);
    this.uninstallPatch = null;
    this.requestExplorerSort();
  }
  // ------------------------------------------------------------------
  // Patching the file explorer
  // ------------------------------------------------------------------
  getExplorerView() {
    var _a;
    const leaf = this.app.workspace.getLeavesOfType("file-explorer")[0];
    return (_a = leaf == null ? void 0 : leaf.view) != null ? _a : null;
  }
  /** Returns true once the explorer view has been patched. */
  patchFileExplorer() {
    if (this.uninstallPatch)
      return true;
    const view = this.getExplorerView();
    if (!view)
      return false;
    const proto = Object.getPrototypeOf(view);
    if (typeof proto.getSortedFolderItems !== "function") {
      console.warn(
        "[Explorer Sort] This Obsidian version does not expose getSortedFolderItems; custom sorting is unavailable."
      );
      return true;
    }
    const plugin = this;
    this.uninstallPatch = around(proto, {
      getSortedFolderItems(old) {
        return function(folder) {
          const items = old.call(this, folder);
          if (!plugin.data.enabled)
            return items;
          const order = plugin.data.orders[folder.path];
          if (!order || order.length === 0)
            return items;
          return plugin.applyOrder(items, order);
        };
      }
    });
    this.register(() => {
      var _a;
      (_a = this.uninstallPatch) == null ? void 0 : _a.call(this);
      this.uninstallPatch = null;
    });
    this.requestExplorerSort();
    return true;
  }
  /**
   * Reorders explorer items: names present in `order` come first (in that
   * order); anything else (e.g. newly created files) keeps Obsidian's
   * default order and is appended at the end.
   */
  applyOrder(items, order) {
    const position = /* @__PURE__ */ new Map();
    order.forEach((name, i) => position.set(name, i));
    const known = [];
    const unknown = [];
    for (const item of items) {
      if (position.has(item.file.name))
        known.push(item);
      else
        unknown.push(item);
    }
    known.sort(
      (a, b) => {
        var _a, _b;
        return ((_a = position.get(a.file.name)) != null ? _a : 0) - ((_b = position.get(b.file.name)) != null ? _b : 0);
      }
    );
    return known.concat(unknown);
  }
  requestExplorerSort() {
    var _a;
    const view = this.getExplorerView();
    (_a = view == null ? void 0 : view.requestSort) == null ? void 0 : _a.call(view);
  }
  // ------------------------------------------------------------------
  // Order manipulation
  // ------------------------------------------------------------------
  /** The children of a folder in the order they are currently displayed. */
  getDisplayedChildNames(folder) {
    const view = this.getExplorerView();
    if (view == null ? void 0 : view.getSortedFolderItems) {
      return view.getSortedFolderItems(folder).map((i) => i.file.name);
    }
    return folder.children.map((c) => c.name);
  }
  async setOrder(folder, names) {
    this.data.orders[folder.path] = names;
    await this.saveData(this.data);
    this.requestExplorerSort();
  }
  async clearOrder(folder) {
    delete this.data.orders[folder.path];
    await this.saveData(this.data);
    this.requestExplorerSort();
  }
  async clearAllOrders() {
    this.data.orders = {};
    await this.saveData(this.data);
    this.requestExplorerSort();
  }
  async saveSettings() {
    await this.saveData(this.data);
    this.requestExplorerSort();
  }
  /**
   * Moves a file/folder within its parent.
   * `target` is either a relative step or an absolute edge.
   */
  async moveItem(file, target) {
    const parent = file.parent;
    if (!parent)
      return;
    const names = this.getDisplayedChildNames(parent);
    const index = names.indexOf(file.name);
    if (index === -1)
      return;
    names.splice(index, 1);
    let newIndex;
    switch (target) {
      case "up":
        newIndex = Math.max(0, index - 1);
        break;
      case "down":
        newIndex = Math.min(names.length, index + 1);
        break;
      case "top":
        newIndex = 0;
        break;
      case "bottom":
        newIndex = names.length;
        break;
    }
    names.splice(newIndex, 0, file.name);
    await this.setOrder(parent, names);
  }
  // ------------------------------------------------------------------
  // UI hooks
  // ------------------------------------------------------------------
  registerFileMenu() {
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!this.data.enabled || !file.parent)
          return;
        const parent = file.parent;
        menu.addSeparator();
        menu.addItem(
          (item) => item.setTitle("Move up").setIcon("arrow-up").setSection("explorer-sort").onClick(() => this.moveItem(file, "up"))
        );
        menu.addItem(
          (item) => item.setTitle("Move down").setIcon("arrow-down").setSection("explorer-sort").onClick(() => this.moveItem(file, "down"))
        );
        menu.addItem(
          (item) => item.setTitle("Move to top").setIcon("arrow-up-to-line").setSection("explorer-sort").onClick(() => this.moveItem(file, "top"))
        );
        menu.addItem(
          (item) => item.setTitle("Move to bottom").setIcon("arrow-down-to-line").setSection("explorer-sort").onClick(() => this.moveItem(file, "bottom"))
        );
        menu.addItem(
          (item) => item.setTitle("Reorder folder contents\u2026").setIcon("list-ordered").setSection("explorer-sort").onClick(() => {
            const folder = file instanceof import_obsidian3.TFolder ? file : parent;
            new ReorderModal(this.app, this, folder).open();
          })
        );
      })
    );
  }
  registerCommands() {
    const moveCommand = (id, name, target) => {
      this.addCommand({
        id,
        name,
        checkCallback: (checking) => {
          const file = this.app.workspace.getActiveFile();
          if (!file || !file.parent)
            return false;
          if (!checking)
            void this.moveItem(file, target);
          return true;
        }
      });
    };
    moveCommand("move-active-file-up", "Move active file up in explorer", "up");
    moveCommand("move-active-file-down", "Move active file down in explorer", "down");
    moveCommand("move-active-file-top", "Move active file to top of its folder", "top");
    moveCommand("move-active-file-bottom", "Move active file to bottom of its folder", "bottom");
    this.addCommand({
      id: "reorder-current-folder",
      name: "Reorder contents of active file's folder",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file || !file.parent)
          return false;
        if (!checking)
          new ReorderModal(this.app, this, file.parent).open();
        return true;
      }
    });
    this.addCommand({
      id: "toggle-custom-sorting",
      name: "Toggle custom sorting on/off",
      callback: async () => {
        this.data.enabled = !this.data.enabled;
        await this.saveSettings();
        new import_obsidian3.Notice(
          `Explorer Sort: custom sorting ${this.data.enabled ? "enabled" : "disabled"}`
        );
      }
    });
  }
  // ------------------------------------------------------------------
  // Keeping stored orders in sync with vault changes
  // ------------------------------------------------------------------
  registerVaultEvents() {
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        void this.handleRename(file, oldPath);
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        void this.handleDelete(file);
      })
    );
  }
  parentPathOf(path) {
    const idx = path.lastIndexOf("/");
    return idx === -1 ? "/" : path.substring(0, idx);
  }
  nameOf(path) {
    const idx = path.lastIndexOf("/");
    return idx === -1 ? path : path.substring(idx + 1);
  }
  async handleRename(file, oldPath) {
    var _a, _b;
    let changed = false;
    const oldParentPath = this.parentPathOf(oldPath);
    const oldName = this.nameOf(oldPath);
    const newParentPath = (_b = (_a = file.parent) == null ? void 0 : _a.path) != null ? _b : "/";
    if (file instanceof import_obsidian3.TFolder) {
      const prefix = oldPath + "/";
      for (const key of Object.keys(this.data.orders)) {
        if (key === oldPath || key.startsWith(prefix)) {
          const newKey = file.path + key.substring(oldPath.length);
          this.data.orders[newKey] = this.data.orders[key];
          delete this.data.orders[key];
          changed = true;
        }
      }
    }
    const oldParentOrder = this.data.orders[oldParentPath];
    if (oldParentOrder) {
      const idx = oldParentOrder.indexOf(oldName);
      if (idx !== -1) {
        if (oldParentPath === newParentPath) {
          oldParentOrder[idx] = file.name;
        } else {
          oldParentOrder.splice(idx, 1);
        }
        changed = true;
      }
    }
    if (changed) {
      await this.saveData(this.data);
      this.requestExplorerSort();
    }
  }
  async handleDelete(file) {
    let changed = false;
    const prefix = file.path + "/";
    for (const key of Object.keys(this.data.orders)) {
      if (key === file.path || key.startsWith(prefix)) {
        delete this.data.orders[key];
        changed = true;
      }
    }
    const parentPath = this.parentPathOf(file.path);
    const parentOrder = this.data.orders[parentPath];
    if (parentOrder) {
      const idx = parentOrder.indexOf(file.name);
      if (idx !== -1) {
        parentOrder.splice(idx, 1);
        changed = true;
      }
    }
    if (changed)
      await this.saveData(this.data);
  }
};

/* nosourcemap */